### PR TITLE
Add an Omnigraffle release of the stencils

### PR DESCRIPTION
**Pull request by bhdicaire**
Hello David,

As you know Visio is not available on MacOs, [Omnigraffle](https://www.omnigroup.com/omnigraffle) is the most popular alternative. I have converted your current Azure_All-Icons_V-3.5.vss to a stencil as-is. 

I appreciate your initiative and I'm ready to release new omnigraffle version in the future.

### CODE REVIEW

**Comment by David-Summers** [comment]
Merci et Bonjour Benoit

I had not considered Mac users for this design resource, I could include an Onmi version but I have no way to test that it works as good as the Visio version. I just read that there can be issues with shadows and layers when importing from the visio format, my stencil currently has shadows. I take it that you are opening the VSSX in Omni and then exporting it back out in Omni format? Could you post an example pic of a complex icon in omni format, Azure Purview would be a good one to use. Are you aware of a Windows process that can convert between the 2 formats or if one of the native Visio stencil save formats would be compatible (below list for export options) - Asking as it would be more efficient for me to add this export option in my build process.

image

Thank you once again, Dave

**Comment by bhdicaire** [comment]
Bonjour Dave,

You don't use layers so this is one less thing to worry about. I did not saw any issue with shadows but it's does not mean much ;) 

As far as I know, the OmniGraffle file format is not public thus it'll be difficult to create a stencil programatically. OmniGroup is a small organization, I can send an email to the president with you in CC about it.

I designed a small diagram with several icons and saved it in native format format and then export it to PNG, PDF and Visio. You'll be able view the artefact from different perspectives. Of course, I can schedule a zoom conference with you and share my desktop. You'll be able to assess it properly.

Best regards, Benoit
[Test Azure-Design.zip](https://github.com/David-Summers/Azure-Design/files/6469586/Test.Azure-Design.zip)

**Comment by David-Summers** [comment]
Interesting the import process does not like the shading Left=YourCopy Right=Origional for some reason the darker shading is being turned into white. 

image

[Import-Test.zip](https://github.com/David-Summers/Azure-Design/files/6471231/Import-Test.zip)

Out of interest I attached a stencil with 2 versions of the Purview icon with and without shadow. Keen to see if there is a difference. If the shadow is causing an issue I can modify the build process to create a version without the shadow

**Comment by bhdicaire** [comment]
Export-test
This is the result.

**Comment by bhdicaire** [comment]
Hi Benoît,

Thanks for getting in touch about this, and apologies of the delayed response to this message!

I had a chance to do some testing with the Visio file attached here (as well as the ones available on the linked Github repo) and it certainly appears as though something about these files is giving our import function some trouble. The shadow settings that were adjusted in the test file seemed like a good theory, and its certainly possible that things like shadows may have some quirks when being imported, but in this case that doesn’t seem to have been related to the bigger issue here, which is the washed out appearance of some of these icons.

I wasn’t able to trace that back to a specific setting in Visio, but it appears as though on import some of the gradient settings aren’t being carried over correctly (which is why they fade to white.) Interestingly, the source SVG images do seem to import into OmniGraffle directly without that issue.

I’ll make sure that a bug report gets logged about that problem on our end, so thanks for pointing it out! Hopefully this is something that can be improved on in a future update.

Please let me know if you have any questions or if there’s anything we can do to assist further.

Best,

The Omni Group

**Comment by bhdicaire** [comment]
The OG issue #2512977 has been confirmed by Omnigroup and there is no specific timeframe for resolution.

I recommend that we close this merge request and forget about it :(

Thanks for your support.

**Pull request closed without merging**
